language: go

go: "1.10"

git:
  depth: false

go_import_path: github.com/containous/traefik

env:
  global:
    - REPO: $TRAVIS_REPO_SLUG
    - VERSION: $TRAVIS_TAG
    - CODENAME: tetedemoine
    - N_MAKE_JOBS: 2

addons:
  sonarcloud:
    organization: "bellingard"
    token:
      secure: "QtpvnhFJ0FL/l+QrJmph6hOYxS68aksxUrm7gsqH3oMfLAGcnM+ts41EUkS8FGi5ZOgNHs6NpNCtSJ/hjHx0xSNldEOVCx2LGOIGcHaTTIp1cbSJZ8bclJIYqRQUZLOD08zXBTHU1s+WwIpSq6z1qd7kbZ4RtZbCcHK4tQCUVkygIuEQfiCnPGlcTh2L1CpsFmIRQzV45iKB65LoP5y/f+RQCt13TI9wAKSnsjNlNlcAmu155dVsQhRJaQs1UtBu0TUcPnr4TRsq7ZfwsM42sKy0F29qVkiCg20D0fMLaEoAtyXHQ131U20wRenp0+rJaVqnXS0MuZ9MzxhEaJxzRwcUY0xPfds6st3fvGCEBVrngwkoDXmucTMavNrQQPcFUxDDZy/Y/7kTuNowotRlZKmhBuXJK5zPlTJcXIE30y91OS1rjKBxHPuDWAPwNhPOwWH6pD2l36gP9TL+8NHoCGA28YPkY97PZwXXQl0fh42dw1snyR8CFjHB03ImkJ4ElNo4aXpf4dq9XhevSvDDyc1skwetpV2sLo2Lq4xSgqVrBd4ov7Z3+TbRVeDyfphPEiMa0mJnCP9r8TpA+Byn81hIP979KHZ5fxB7OIyElK/cQ70CbRsYTPPTsyCkmHDoc4kTTwZ+CZM3ivXXG2y8kfOP++hu7p0YXCOpOfSKYmI="
      
install:
  # Installs Go Meta Linter (Golint and Go vet are also supported independently)
  - go get -u gopkg.in/alecthomas/gometalinter.v2
  - $GOPATH/bin/gometalinter.v2 --install

script:
  # Execute Go Meta Linter
  - $GOPATH/bin/gometalinter.v2 ./... > gometalinter-report.out || true
  # Execute tests and coverage
  - go test -json > report.json
  - go test -coverprofile=coverage.out
  # And then execute SonarCloud analysis which will run its own code analysis, and also reuse the linters' results
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
